name: Build eudplib 
on:
  release:
    types: [created]
  workflow_dispatch: 
    
jobs:
  build_libepScript:
    strategy: 
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      
      - name: Configure CMake
        run: cmake -B /src/epscript/build -S /src/epscript
              -DCMAKE_BUILD_TYPE=Release
        
      - name: Build
        run: cmake --build /src/epscript/build --config Release