name: Build eudplib 
on:
  release:
    types: [created]
  workflow_dispatch: 
  
env:
  BUILD_TYPE: Release
    
jobs:
  build_libepScript:
    strategy: 
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/src/epscript/build -S ${{ github.workspace}}/src/epscript
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        
      - name: Build
        run: cmake --build ${{ github.workspace }}/src/epscript/build --config ${{ env.BUILD_TYPE }}