name: Build eudplib 
on:
  release:
    types: [created]
  workflow_dispatch: 
  
env:
  BUILD_TYPE: Release
    
jobs:
  build_libepScript:
    strategy: 
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      
      - name: Configure CMake
        run: 
          if [[ ${{ matrix.os }} == windows-* ]]; then
            cmake -B ${{ github.workspace }}\\src\\epscript\\build \
                  -S ${{ github.workspace }}\\src\\epscript \
                  -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          else
            cmake -B ${{ github.workspace }}/src/epscript/build \
                  -S ${{ github.workspace }}/src/epscript \
                  -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          fi
        
        
      - name: Build
        run: |
          chmod -R 777 ${{ github.workspace }}/src/epscript
          if [[ ${{ matrix.os }} == windows-* ]]; then
            cmake --build ${{ github.workspace }}\\src\\epscript\\build --config ${{ env.BUILD_TYPE }}
          else
            cmake --build ${{ github.workspace }}/src/epscript/build --config ${{ env.BUILD_TYPE }}
          fi